project:
  type: book
#  output-dir: _book

book:
  title: "Exploring Calculus with Python"
#  author: "Adam Spiegler, University of Colorado Denver"
  reader-mode: true
#  date: "`r Sys.Date()`"

  page-footer:
      left: |
        Exploring Calculus with Python
      right: |
        ![Creative Commons License](https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png) [CC BY-N-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)
#        This book was built with <a href="https://quarto.org/">Quarto</a>.
#  cover-image: cover.png

  chapters:
    - index.qmd
    - Lab1-Getting-Started-with-Colab-Python.ipynb
    - Lab2-Plotting-and-Solving-Equations.ipynb
    - Lab3-Linear-Regression.ipynb
    - Lab4-Derivatives-with-Water-Level.ipynb
    - Lab5-Symbolic-Differentiation-Marginal-Cost.ipynb
    - Lab6-Optimization.ipynb
    - Lab7-Definite-Integrals-and-Accumulated-Change.ipynb
    - Lab8-Symbolic-Integration.ipynb

#bibliography: references.bib


#format:
#  html: 
#    theme: flatly
#    #cover-image: https://geocompr.robinlovelace.net/images/cover.png
#    code-link: true
#    template-partials: [toc.html,title-block.html]
#    toc-title: "On this page"
#    code-overflow: wrap
#    toc-depth: 5
#    number-sections: false


format:
  html:
#    toc: true
    toc_depth: 4
#    theme: cerulean
    theme: cosmo
#    number-depth: 4
    number-sections: false
##  pdf:
##    documentclass: scrreprt
##    number-sections: false
##  epub:
##    cover-image: cover.png

jupyter: python3

execute:
  eval: false

editor: source



# quarto publish gh-pages

